package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteMiscItem - Generated by CreateKKAdminCustomEng
 */
public class DeleteMiscItem
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteMiscItem(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteMiscItem(String sessionId, int miTypeId) throws KKAdminException
     {
         kkAdminEng.deleteMiscItem(sessionId, miTypeId);
     }
}
