package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DoesCustomerExistForEmail - Generated by CreateKKAdminCustomEng
 */
public class DoesCustomerExistForEmail
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DoesCustomerExistForEmail(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean doesCustomerExistForEmail(String sessionId, String emailAddr) throws KKAdminException
     {
         return kkAdminEng.doesCustomerExistForEmail(sessionId, emailAddr);
     }
}
