package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCategoriesPerTagGroup - Generated by CreateKKAdminCustomEng
 */
public class GetCategoriesPerTagGroup
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCategoriesPerTagGroup(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int[] getCategoriesPerTagGroup(String sessionId, int tagGroupId) throws KKAdminException
     {
         return kkAdminEng.getCategoriesPerTagGroup(sessionId, tagGroupId);
     }
}
