package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCategoriesToTagGroups - Generated by CreateKKAdminCustomEng
 */
public class GetCategoriesToTagGroups
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCategoriesToTagGroups(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCategoryToTagGroup[] getCategoriesToTagGroups(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getCategoriesToTagGroups(sessionId);
     }
}
