package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetFileContents - Generated by CreateKKAdminCustomEng
 */
public class GetFileContents
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetFileContents(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getFileContents(String sessionId, String fileName) throws KKAdminException
     {
         return kkAdminEng.getFileContents(sessionId, fileName);
     }
}
