package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetManufacturer - Generated by CreateKKAdminCustomEng
 */
public class GetManufacturer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetManufacturer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminManufacturer getManufacturer(int manufacturerId) throws KKAdminException
     {
         return kkAdminEng.getManufacturer(manufacturerId);
     }
}
