package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetOrdersCreatedSince - Generated by CreateKKAdminCustomEng
 */
public class GetOrdersCreatedSince
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetOrdersCreatedSince(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrder[] getOrdersCreatedSince(String sessionId, Calendar since, int languageId) throws KKAdminException
     {
         return kkAdminEng.getOrdersCreatedSince(sessionId, since, languageId);
     }
}
