package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductCountPerTemplate - Generated by CreateKKAdminCustomEng
 */
public class GetProductCountPerTemplate
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductCountPerTemplate(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int getProductCountPerTemplate(String sessionId, int templateId) throws KKAdminException
     {
         return kkAdminEng.getProductCountPerTemplate(sessionId, templateId);
     }
}
