package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - LogMsg - Generated by CreateKKAdminCustomEng
 */
public class LogMsg
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public LogMsg(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void logMsg(int level, String message) throws KKAdminException
     {
         kkAdminEng.logMsg(level, message);
     }
}
