package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SetProductAvailabilityWithOptions - Generated by CreateKKAdminCustomEng
 */
public class SetProductAvailabilityWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SetProductAvailabilityWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void setProductAvailabilityWithOptions(String sessionId, String sku, int id, Calendar dateAvailable, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         kkAdminEng.setProductAvailabilityWithOptions(sessionId, sku, id, dateAvailable, mgrOptions);
     }
}
