package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateMiscItems - Generated by CreateKKAdminCustomEng
 */
public class UpdateMiscItems
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateMiscItems(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateMiscItems(String sessionId, AdminMiscItem[] miTypes) throws KKAdminException
     {
         kkAdminEng.updateMiscItems(sessionId, miTypes);
     }
}
