package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateTag - Generated by CreateKKAdminCustomEng
 */
public class UpdateTag
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateTag(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int updateTag(String sessionId, AdminTag tag) throws KKAdminException
     {
         return kkAdminEng.updateTag(sessionId, tag);
     }
}
