package com.konakart.app;

/**
 *  The KonaKart Custom Engine - CheckSession - Generated by CreateKKCustomEng
 */
public class CheckSession
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CheckSession(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int checkSession(String sessionId) throws KKException
     {
         return kkEng.checkSession(sessionId);
     }
}
