package com.konakart.app;

/**
 *  The KonaKart Custom Engine - DeleteCookie - Generated by CreateKKCustomEng
 */
public class DeleteCookie
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public DeleteCookie(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void deleteCookie(String customerUuid, String attrId) throws KKException
     {
         kkEng.deleteCookie(customerUuid, attrId);
     }
}
