package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetConfigurations - Generated by CreateKKCustomEng
 */
public class GetConfigurations
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurations(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public KKConfigurationIf[] getConfigurations() throws KKException
     {
         return kkEng.getConfigurations();
     }
}
