package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetSecretKeyForOrderId - Generated by CreateKKCustomEng
 */
public class GetSecretKeyForOrderId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSecretKeyForOrderId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getSecretKeyForOrderId(int orderId) throws KKException
     {
         return kkEng.getSecretKeyForOrderId(orderId);
     }
}
