package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetSku - Generated by CreateKKCustomEng
 */
public class GetSku
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSku(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getSku(OrderProductIf orderProd) throws KKException
     {
         return kkEng.getSku(orderProd);
     }
}
